version: '3.9'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:80"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
